### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Unet:

### ISSUE THREAD

**Issue by zzrrll** [jiwd123/improved_unet#2]
使用predict时：
RuntimeError: Error(s) in loading state_dict for Unet:
	Missing key(s) in state_dict: "up_concat4.cbam.mlp.0.weight", "up_concat4.cbam.mlp.2.weight", "up_concat4.cbam.conv.weight", "up_concat3.cbam.mlp.0.weight", "up_concat3.cbam.mlp.2.weight", "up_concat3.cbam.conv.weight", "up_concat2.cbam.mlp.0.weight", "up_concat2.cbam.mlp.2.weight", "up_concat2.cbam.conv.weight", "up_concat1.cbam.mlp.0.weight", "up_concat1.cbam.mlp.2.weight", "up_concat1.cbam.conv.weight". 
尝试在unet中改了这一行， self.net.load_state_dict(torch.load(self.model_path, map_location=device,),strict=False)
RuntimeError: Given groups=1, weight of size [64, 1024, 1, 1], expected input[1, 512, 1, 1] to have 1024 channels, but got 512 channels instead.
该如何修改

**Comment by jiwd123** [comment]
请注意unet.py的第12行与train.py的第11行是否保持一致，这一行代表使用不同的网络，以上报错信息是没有在权重中找到CBAM模块，尝试将unet.py中的第12行from nets.unet import Unet 改为from nets.unet import Unet。

**Comment by zzrrll** [comment]
谢谢，可以预测了，我想请问我现在想进行根系重建，需要运行的代码有哪些

**Comment by jiwd123** [comment]
可以试试CycleGAN，Pix2pix和EnlightenGAN。Improved_UNet属于语义分割网络，无法实现根系重构
